language: python

cache: pip
before_cache:
  - rm ~/.cache/pip/log/debug.log

python:
  - "3.6"

jobs:
  include:
    - stage: cardboard linter
      install:
        - pip install --upgrade cardboardlint pylint
      script:
        # Run cardboardlinter, in case of pull requests
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            cardboardlinter --refspec $TRAVIS_BRANCH -n auto;
          fi
    - stage: python unit tests
      install:
        - pip install --upgrade -r requirements_tests.txt
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            python -m unittest;
          fi
    - stage: python integration tests
      install:
        - pip install --upgrade -r requirements.txt
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            python feeding_test.py;
          fi
